### ISSUE TITLE
如何设置 rofi 打开 ranger 默认使用 xfce4-terminal

### ISSUE THREAD

**Issue by im55cc** [itgoyo/i3#8]
![image](https://user-images.githubusercontent.com/10059014/65371319-19a51d80-dc95-11e9-9540-ab7223adfb30.png)

**Comment by itgoyo** [comment]
@im55cc 关于你说这个ranger怎么选择终端启动，这个我也没法回答，因为我对于rofi不是很熟悉，但是你可以换种思路，就是绑定快捷键 然后让他执行 "xfce4-terminal ranger "这样子就能满足你的需求了。

**Comment by im55cc** [comment]
好的，谢谢。
